### ISSUE TITLE
Expand animation in tab bar controller

### ISSUE THREAD

**Issue by ivnsch** [ifitdoesntwork/DAExpandAnimation#2]
Hi,
I downloaded the demo project and am trying to do the expand transition inside a tab bar controller, such that the tab bar keeps unchanged (the transition would happen behind the tab bar basically). Not succeeding so far. Tried among other things to create a container view inside the tab, which embeds the table view controller, which has the modal segue to the expanded view controller... the tab bar always hides. Any idea? Thanks!

**Comment by ifitdoesntwork** [comment]
There's the expandedViewFrame property on the DAExpandAnimation class. You can set it so the expanded view won't cover the tab bar.

**Comment by ivnsch** [comment]
The problem with this is that it animates with the tabs, such that the tab bar slides down and then reappears, it also shows a gap during the animation in which you can see the cells behind and after it finishes the tabs are not interactive... I did some tests with a normal modal and it was not possible to adjust the actual controller's frame...

**Comment by ivnsch** [comment]
I'm trying now to do this animation without the controller's transition. Looking good. The gap is because the shorter frame as well as the bottom snapshot are animated at the same time and snapshot will move faster.
