### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by dziedziela** [ifitdoesntwork/DAExpandAnimation#3]
Hello,

I found an issue when is embedded in a Navigation Controller. The animation is not that smooth anymore. Have any idea how to fix it?

Thanks

**Comment by efremidze** [comment]
Can you give more details?

**Comment by fe9lix** [comment]
Try moving the call inView.addSubview(frontView) in DAExpandAnimation to a line _before_ the frontView frame is set (currently the frontView is added after setting the frame). This fixes a NavigationBar related "flickering" issue for me. I've also opened a pull request containing the change.
